# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'job_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'job_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  job_dbt:
    # Config for raw schema models
    raw:
      +materialized: view
      +schema: raw
      
    # Config for staging schema models
    staging:
      +materialized: view
      +schema: staging
      
    # Config for intermediate models
    int:
      +materialized: view
      +schema: staging
      
    # Config for marts (dimensions and facts)
    # Note: Individual models override this with incremental materialization
    # to preserve rank_score and rank_explain during incremental runs
    marts:
      +materialized: table
      +schema: marts

# Seed configurations
seeds:
  job_dbt:
    +schema: staging
    +quote_columns: false

# Documentation
docs-paths: ["docs"]

