version: 2

models:
  - name: stg_job_postings
    description: "Staging table for job postings with normalized fields and deduplication"
    columns:
      - name: hash_key
        description: "Primary deduplication key: md5(lower(company)||'|'||lower(title)||'|'||lower(location))"
        tests:
          - unique
          - not_null
      
      - name: provider_job_id
        description: "Job ID from the source provider (if available)"
      
      - name: job_link
        description: "Canonical URL to the job posting"
      
      - name: job_title
        description: "Raw job title from the provider"
        tests:
          - not_null
      
      - name: company
        description: "Raw company name from the provider"
        tests:
          - not_null
      
      - name: company_size
        description: "Company size bucket (defaults to 'unknown' if not provided)"
        tests:
          - not_null
          - accepted_values:
              values: ['1-10', '11-50', '51-200', '201-500', '501-1000', '1001-5000', '5001+', 'unknown']
              config:
                severity: warn  # Warn instead of error to allow new values during development
      
      - name: location
        description: "Raw location string from the provider"
        tests:
          - not_null
      
      - name: remote_type
        description: "Type of remote work arrangement"
        tests:
          - not_null
          - accepted_values:
              values: ['remote', 'hybrid', 'onsite', 'unknown']
              quote: false
      
      - name: contract_type
        description: "Type of employment contract"
        tests:
          - not_null
          - accepted_values:
              values: ['full_time', 'part_time', 'contract', 'intern', 'temp', 'unknown']
              quote: false
      
      - name: salary_min
        description: "Minimum salary in original currency"
      
      - name: salary_max
        description: "Maximum salary in original currency"
      
      - name: salary_currency
        description: "ISO 4217 currency code"
      
      - name: description
        description: "Full job description text"
      
      - name: skills_raw
        description: "Array of skills parsed from the provider (if available)"
      
      - name: posted_at
        description: "When the job was originally posted (provider timestamp)"
      
      - name: apply_url
        description: "URL where candidates can apply"
      
      - name: source
        description: "Name of the source API/provider"
        tests:
          - not_null
      
      - name: first_seen_at
        description: "Timestamp when this job posting was first ingested into our system"
        tests:
          - not_null
      
      - name: last_seen_at
        description: "Timestamp when this job posting was most recently seen"
        tests:
          - not_null

seeds:
  - name: remote_type
    description: "Reference table for valid remote work types"
    columns:
      - name: remote_type
        description: "Valid remote type value"
        tests:
          - unique
          - not_null
      - name: description
        description: "Human-readable description"
  
  - name: contract_type
    description: "Reference table for valid contract types"
    columns:
      - name: contract_type
        description: "Valid contract type value"
        tests:
          - unique
          - not_null
      - name: description
        description: "Human-readable description"
  
  - name: company_size
    description: "Reference table for valid company size buckets"
    columns:
      - name: company_size
        description: "Valid company size bucket"
        tests:
          - unique
          - not_null
      - name: description
        description: "Human-readable description"

