version: 2

# NOTE: stg_job_postings model has been removed.
# The Python normalizer service now populates staging.job_postings_stg directly.
# Tests for job_postings_stg are in sources.yml instead.
# 
# This file now only contains seed definitions for enum reference tables.

seeds:
  - name: remote_type
    description: "Reference table for valid remote work types"
    columns:
      - name: remote_type
        description: "Valid remote type value"
        tests:
          - unique
          - not_null
      - name: description
        description: "Human-readable description"
  
  - name: contract_type
    description: "Reference table for valid contract types"
    columns:
      - name: contract_type
        description: "Valid contract type value"
        tests:
          - unique
          - not_null
      - name: description
        description: "Human-readable description"
  
  - name: company_size
    description: "Reference table for valid company size buckets"
    columns:
      - name: company_size
        description: "Valid company size bucket"
        tests:
          - unique
          - not_null
      - name: description
        description: "Human-readable description"

